import { ReactNode } from 'react';

import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';

import '@/app/globals.css';
import MobileRestriction from '@/components/layout/MobileRestriction';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Fillout Assessment',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): ReactNode {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased overflow-hidden md:overflow-auto`}
      >
        <MobileRestriction />
        {children}
      </body>
    </html>
  );
}
